@startuml

!theme sunlust
skinparam style strictuml
autoactivate on

title "Sequence Diagram for InputKeyword Execution"

box GameThread
    participant "XML-RPC Server" as HTTP
    participant "Automation Driver" as Driver
end box

box ThreadPool
    participant "Robot Integration" as Robot
    participant "InputKeyword" as Keyword
end box

' Incoming Request
[-> HTTP : "run_keyword"
HTTP -> HTTP : Parse request
return name, args
HTTP -> Robot : KeywordManager::Execute(name, args)
Robot -> Keyword ** : Create Keyword
Robot -> Keyword : Execute(args)

' Create Keyword and locate Element
Keyword -> Driver ** : CreateDriver()
Driver --> Keyword : driver
Keyword -> Driver : FindElement(locator)
return element

' Perform Action on Element
Keyword -> Driver : Click()
Driver ->> Driver : Perform()
return success
return success
destroy Driver

' Generate Response
Keyword -> Keyword : GenerateResponse(success)
return response
Keyword --> Robot : response
destroy Keyword
Robot --> HTTP : response

' Finish Request
HTTP -> HTTP : Parse response
return xmlResponse
[<- HTTP -- : xmlResponse

@enduml